create table if not exists screenshot_task (
    task_id varchar(64) not null,
    file_name varchar(255) not null,
    content_type varchar(128) not null,
    file_size bigint not null,
    sample_label varchar(128) not null,
    status varchar(64) not null,
    server_ocr_enabled boolean not null,
    privacy_policy varchar(512) not null,
    created_at varchar(64) not null,
    payload_json clob,
    primary key (task_id)
);

create table if not exists ocr_task (
    ocr_task_id varchar(64) not null,
    screenshot_task_id varchar(64) not null,
    ocr_provider varchar(128) not null,
    raw_text clob,
    status varchar(64) not null,
    analysis_allowed boolean not null,
    fields_json clob,
    payload_json clob,
    parsed_at varchar(64) not null,
    primary key (ocr_task_id),
    constraint fk_ocr_task_screenshot_task
        foreign key (screenshot_task_id) references screenshot_task (task_id)
);

create index if not exists idx_ocr_task_screenshot_task_id
    on ocr_task (screenshot_task_id);

create table if not exists ocr_confirmed_snapshot (
    snapshot_id varchar(64) not null,
    ocr_task_id varchar(64) not null,
    source_type varchar(64) not null,
    snapshot_status varchar(64) not null,
    analysis_allowed boolean not null,
    risk_preference varchar(64),
    budget_amount decimal(18, 2),
    currency varchar(16),
    matches_json clob,
    markets_json clob,
    payload_json clob,
    confirmed_at varchar(64) not null,
    primary key (snapshot_id),
    constraint fk_ocr_confirmed_snapshot_ocr_task
        foreign key (ocr_task_id) references ocr_task (ocr_task_id)
);

create index if not exists idx_ocr_confirmed_snapshot_ocr_task_id
    on ocr_confirmed_snapshot (ocr_task_id);

create table if not exists analysis_report (
    report_id varchar(64) not null,
    snapshot_id varchar(64) not null,
    input_source_type varchar(64) not null,
    engine_type varchar(64) not null,
    report_status varchar(64) not null,
    probability_analysis_json clob,
    risk_warnings_json clob,
    simulated_selections_json clob,
    compliance_notice varchar(512) not null,
    payload_json clob,
    generated_at varchar(64) not null,
    primary key (report_id)
);

create index if not exists idx_analysis_report_snapshot_id
    on analysis_report (snapshot_id);

create table if not exists simulated_plan (
    plan_id varchar(64) not null,
    plan_type varchar(64) not null,
    plan_status varchar(64) not null,
    report_id varchar(64) not null,
    snapshot_id varchar(64) not null,
    currency varchar(16),
    budget_amount decimal(18, 2),
    status_flow_json clob,
    plan_snapshot_json clob,
    compliance_notice varchar(512) not null,
    operator_note varchar(512),
    payload_json clob,
    created_at varchar(64) not null,
    updated_at varchar(64) not null,
    primary key (plan_id)
);

create index if not exists idx_simulated_plan_report_id
    on simulated_plan (report_id);

create index if not exists idx_simulated_plan_status_updated_at
    on simulated_plan (plan_status, updated_at);

create table if not exists simulated_plan_item (
    plan_item_id varchar(64) not null,
    plan_id varchar(64) not null,
    match_id varchar(128) not null,
    match_date varchar(32),
    league varchar(128),
    home_team varchar(128),
    away_team varchar(128),
    kickoff_time varchar(64),
    play_type varchar(64) not null,
    selection varchar(64) not null,
    odds decimal(18, 2),
    stake_amount decimal(18, 2),
    item_status varchar(64) not null,
    note varchar(512),
    payload_json clob,
    created_at varchar(64) not null,
    primary key (plan_item_id),
    constraint fk_simulated_plan_item_plan
        foreign key (plan_id) references simulated_plan (plan_id)
);

create index if not exists idx_simulated_plan_item_plan_id
    on simulated_plan_item (plan_id);

create index if not exists idx_simulated_plan_item_match_id
    on simulated_plan_item (match_id);

create table if not exists public_result_snapshot (
    result_snapshot_id varchar(64) not null,
    match_id varchar(128) not null,
    match_date varchar(32),
    league varchar(128),
    home_team varchar(128),
    away_team varchar(128),
    kickoff_time varchar(64),
    home_score int not null,
    away_score int not null,
    result_status varchar(64) not null,
    source_name varchar(128) not null,
    source_url varchar(512) not null,
    source_license varchar(255) not null,
    fetched_at varchar(64) not null,
    confidence decimal(8, 4),
    payload_json clob,
    primary key (result_snapshot_id)
);

create index if not exists idx_public_result_snapshot_match_id
    on public_result_snapshot (match_id);

create table if not exists review_record (
    review_id bigint generated by default as identity,
    plan_id varchar(64) not null,
    review_status varchar(64) not null,
    match_status varchar(64) not null,
    match_confidence decimal(8, 4),
    item_settlements_json clob,
    failure_reasons_json clob,
    strategy_revision_rules_json clob,
    result_source_json clob,
    supported_settlement_statuses_json clob,
    supported_failure_reasons_json clob,
    payload_json clob,
    reviewed_at varchar(64) not null,
    primary key (review_id),
    constraint uq_review_record_plan_id unique (plan_id)
);
