import { isNonNilUuid, validateCandidateBatch, type CandidateBatch, type CandidateIssue, type OcrCandidateField } from './candidates'
import { type PixelRect } from './geometry'

export interface NormalizedOcrWord { text: string; confidence: number; boundingBox?: PixelRect }
export interface NormalizedOcrLine { words: readonly NormalizedOcrWord[] }
export type CreateUuid = () => string
export type MappingResult = { valid: true; value: CandidateBatch; issues: readonly CandidateIssue[] } | { valid: false; issues: readonly CandidateIssue[] }
type Name = OcrCandidateField['fieldName']
type LabelName = Name | 'marketRef'
type Label = { name: LabelName; tokens: readonly string[] }
const LABELS: readonly Label[] = [
  { name: 'matchRef', tokens: ['MATCH', 'REF:'] }, { name: 'marketRef', tokens: ['MARKET', 'REF:'] }, { name: 'matchDate', tokens: ['DATE:'] },
  { name: 'league', tokens: ['LEAGUE:'] }, { name: 'homeTeam', tokens: ['HOME:'] }, { name: 'awayTeam', tokens: ['AWAY:'] }, { name: 'kickoffTime', tokens: ['KICKOFF:'] },
  { name: 'playType', tokens: ['PLAY', 'TYPE:'] }, { name: 'selection', tokens: ['SELECTION:'] }, { name: 'odds', tokens: ['ODDS:'] },
]
// These limits bound synchronous normalized-evidence parsing work; they are not semantic mapping rules.
const MAX_OCR_LINES = 4_096
const MAX_WORDS_PER_LINE = 1_024
const MAX_OCR_WORDS = 65_536
function problem(path: string, code: string, message: string): CandidateIssue { return { path, code, message } }
function plain(value: unknown): value is Record<string, unknown> { if (typeof value !== 'object' || value === null || Array.isArray(value)) return false; try { const prototype = Object.getPrototypeOf(value); return prototype === Object.prototype || prototype === null } catch { return false } }
function own(value: object, key: string): { ok: true; value: unknown } | { ok: false } { try { const descriptor = Object.getOwnPropertyDescriptor(value, key); return descriptor && Object.hasOwn(descriptor, 'value') ? { ok: true, value: descriptor.value } : { ok: false } } catch { return { ok: false } } }
function arrayLength(value: object, path: string, issues: CandidateIssue[]): number | undefined { try { const descriptor = Object.getOwnPropertyDescriptor(value, 'length'); if (!descriptor || !Object.hasOwn(descriptor, 'value') || typeof descriptor.value !== 'number' || !Number.isSafeInteger(descriptor.value) || descriptor.value < 0) { issues.push(problem(`${path}.length`, 'OWN_DATA_REQUIRED', 'length must be an own data safe integer')); return undefined }; return descriptor.value } catch { issues.push(problem(`${path}.length`, 'OWN_DATA_REQUIRED', 'length must be safely readable')); return undefined } }
function strictArrayKeys(value: object, length: number, path: string, issues: CandidateIssue[]): boolean { try { for (const key of Reflect.ownKeys(value)) { if (key === 'length') continue; if (typeof key !== 'string' || !/^(0|[1-9]\d*)$/.test(key) || Number(key) >= length) issues.push(problem(`${path}.${String(key)}`, 'UNKNOWN_ARRAY_PROPERTY', 'arrays allow only length and dense numeric slots')) }; return true } catch { issues.push(problem(path, 'UNREADABLE_ARRAY', 'array keys are not safely readable')); return false } }
function exactRecordKeys(value: object, expected: readonly string[], path: string, issues: CandidateIssue[]): void { try { for (const key of Reflect.ownKeys(value)) if (typeof key !== 'string' || !expected.includes(key)) issues.push(problem(`${path}.${String(key)}`, 'UNKNOWN_PROPERTY', 'unknown property')) } catch { issues.push(problem(path, 'UNREADABLE_RECORD', 'record keys are not safely readable')) } }
function clean(value: string): string { return value.trim().replace(/\s+/g, ' ').replace(/(\p{Script=Han}) (?=\p{Script=Han})/gu, '$1') }
function token(value: unknown): string { return typeof value === 'string' ? clean(value).toUpperCase() : '' }
function labelOf(words: readonly NormalizedOcrWord[]): { label: Label; values: readonly NormalizedOcrWord[] } | undefined { for (const label of LABELS) { if (words.length >= label.tokens.length && label.tokens.every((part, index) => token(words[index]?.text) === part)) return { label, values: words.slice(label.tokens.length) } } return undefined }
function validBox(value: unknown, size: { width: number; height: number }): value is PixelRect { if (!plain(value)) return false; try { if (Reflect.ownKeys(value).some((key) => typeof key !== 'string' || !['x', 'y', 'width', 'height'].includes(key))) return false } catch { return false }; const x = own(value, 'x'); const y = own(value, 'y'); const width = own(value, 'width'); const height = own(value, 'height'); if (!x.ok || !y.ok || !width.ok || !height.ok || [x.value, y.value, width.value, height.value].some((entry) => typeof entry !== 'number' || !Number.isFinite(entry))) return false; const left = x.value as number; const top = y.value as number; const w = width.value as number; const h = height.value as number; return left >= 0 && top >= 0 && w > 0 && h > 0 && left + w <= size.width && top + h <= size.height }
type EvidenceResult = { ok: true; value: { value: string; confidence: number; boundingBox?: PixelRect } } | { ok: false; code: string; message: string }
function evidence(words: readonly NormalizedOcrWord[], size: { width: number; height: number }): EvidenceResult {
  const value = clean(words.map((word) => word.text).join(' ')); if (!value) return { ok: false, code: 'EMPTY_VALUE', message: 'label must have a value' }
  let confidence = Number.POSITIVE_INFINITY; for (const word of words) confidence = Math.min(confidence, word.confidence); if (!Number.isFinite(confidence) || confidence < 0 || confidence > 1) return { ok: false, code: 'INVALID_CONFIDENCE', message: 'value confidence must be finite and within [0,1]' }
  const boxes = words.map((word) => word.boundingBox); const provided = boxes.filter((box) => box !== undefined)
  if (provided.length === 0) return { ok: true, value: { value, confidence } }
  if (provided.length !== words.length || !boxes.every((box) => validBox(box, size))) return { ok: false, code: 'INVALID_VALUE_BBOX', message: 'if one value word has a bbox, every value word must have a valid processed-space bbox' }
  const parsed = boxes as PixelRect[]; let left = Number.POSITIVE_INFINITY; let top = Number.POSITIVE_INFINITY; let right = Number.NEGATIVE_INFINITY; let bottom = Number.NEGATIVE_INFINITY; for (const box of parsed) { left = Math.min(left, box.x); top = Math.min(top, box.y); right = Math.max(right, box.x + box.width); bottom = Math.max(bottom, box.y + box.height) }; return { ok: true, value: { value, confidence, boundingBox: { x: left, y: top, width: right - left, height: bottom - top } } }
}
function idFrom(factory: CreateUuid, path: string, kind: 'entity' | 'field', issues: CandidateIssue[], allocatedEntityKeys: Set<string>, allocatedFieldIds: Set<string>): string | undefined { let id: string; try { id = factory() } catch { issues.push(problem(path, 'INVALID_MAPPER_ID', 'UUID factory failed')); return undefined }; if (!isNonNilUuid(id)) { issues.push(problem(path, 'INVALID_MAPPER_ID', 'UUID factory must return a non-nil UUID')); return undefined }; const normalized = id.toLowerCase(); const allocated = kind === 'entity' ? allocatedEntityKeys : allocatedFieldIds; if (allocated.has(normalized)) { issues.push(problem(path, 'DUPLICATE_MAPPER_ID', 'UUID factory returned an already allocated identifier')); return undefined }; allocated.add(normalized); return id }

export function mapNormalizedOcr(lines: unknown, processedImage: unknown, createUuid: CreateUuid): MappingResult {
  const issues: CandidateIssue[] = []
  try {
    if (!Array.isArray(lines)) return { valid: false, issues: [problem('lines', 'ARRAY_REQUIRED', 'lines must be an array')] }
    const linesLength = arrayLength(lines, 'lines', issues); if (linesLength === undefined) return { valid: false, issues }; if (linesLength > MAX_OCR_LINES) return { valid: false, issues: [...issues, problem('lines', 'MAX_LINES', `must contain at most ${MAX_OCR_LINES} lines`)] }; strictArrayKeys(lines, linesLength, 'lines', issues)
    const image = validateCandidateBatch({ schemaVersion: 'OCR_CANDIDATE_V2', processedImage, fields: [] }); if (!image.valid) return { valid: false, issues: image.issues }
    const size = image.value.processedImage.processedSize; const matches = new Map<string, string>(); const active: { match?: string; market?: string } = {}; const fields: OcrCandidateField[] = []; const tuples = new Set<string>(); const allocatedEntityKeys = new Set<string>(); const allocatedFieldIds = new Set<string>(); let exceededFieldLimit = false; let totalWords = 0
    const add = (entityType: 'MATCH' | 'MARKET', entityKey: string, fieldName: Name, entry: { value: string; confidence: number; boundingBox?: PixelRect }, path: string): void => { if (fields.length >= 256) { issues.push(problem('fields', 'MAX_FIELDS', 'mapper must not create more than 256 candidate fields')); exceededFieldLimit = true; return }; const tuple = `${entityType}:${entityKey}:${fieldName}`; if (tuples.has(tuple)) { issues.push(problem(path, 'DUPLICATE_LABEL', 'repeated label for one entity is ambiguous')); return }; const fieldId = idFrom(createUuid, `${path}.fieldId`, 'field', issues, allocatedEntityKeys, allocatedFieldIds); if (!fieldId) return; tuples.add(tuple); fields.push({ fieldId, entityType, entityKey, fieldName, fieldValue: entry.value, confidence: entry.confidence, ...(entry.boundingBox ? { boundingBox: entry.boundingBox } : {}) }) }
    for (let lineIndex = 0; lineIndex < linesLength; lineIndex += 1) {
      const descriptor = Object.getOwnPropertyDescriptor(lines, String(lineIndex)); if (!descriptor || !Object.hasOwn(descriptor, 'value')) { issues.push(problem(`lines[${lineIndex}]`, 'DENSE_ARRAY_REQUIRED', 'line must be an own data slot')); continue }
      const line = descriptor.value; if (!plain(line)) { issues.push(problem(`lines[${lineIndex}]`, 'PLAIN_RECORD_REQUIRED', 'line must be a plain record')); continue }
      exactRecordKeys(line, ['words'], `lines[${lineIndex}]`, issues)
      const wordsValue = own(line, 'words'); if (!wordsValue.ok || !Array.isArray(wordsValue.value)) { issues.push(problem(`lines[${lineIndex}].words`, 'ARRAY_REQUIRED', 'words must be an array')); continue }
      const wordsLength = arrayLength(wordsValue.value, `lines[${lineIndex}].words`, issues); if (wordsLength === undefined) continue; if (wordsLength > MAX_WORDS_PER_LINE) { issues.push(problem(`lines[${lineIndex}].words`, 'MAX_WORDS_PER_LINE', `must contain at most ${MAX_WORDS_PER_LINE} words`)); return { valid: false, issues } }; if (totalWords + wordsLength > MAX_OCR_WORDS) { issues.push(problem(`lines[${lineIndex}].words`, 'MAX_WORDS_TOTAL', `normalized evidence must contain at most ${MAX_OCR_WORDS} words`)); return { valid: false, issues } }; totalWords += wordsLength; strictArrayKeys(wordsValue.value, wordsLength, `lines[${lineIndex}].words`, issues)
      const words: NormalizedOcrWord[] = []; let malformed = false
      for (let wordIndex = 0; wordIndex < wordsLength; wordIndex += 1) { const wordDescriptor = Object.getOwnPropertyDescriptor(wordsValue.value, String(wordIndex)); if (!wordDescriptor || !Object.hasOwn(wordDescriptor, 'value') || !plain(wordDescriptor.value)) { malformed = true; break }; const raw = wordDescriptor.value; exactRecordKeys(raw, ['text', 'confidence', 'boundingBox'], `lines[${lineIndex}].words[${wordIndex}]`, issues); const text = own(raw, 'text'); const confidence = own(raw, 'confidence'); let bboxDescriptor: PropertyDescriptor | undefined; try { bboxDescriptor = Object.getOwnPropertyDescriptor(raw, 'boundingBox') } catch { issues.push(problem(`lines[${lineIndex}].words[${wordIndex}].boundingBox`, 'OWN_DATA_REQUIRED', 'must be an own data property')); malformed = true; break }; if (!text.ok || typeof text.value !== 'string' || !confidence.ok || typeof confidence.value !== 'number' || !Number.isFinite(confidence.value)) { malformed = true; break }; if (bboxDescriptor && !Object.hasOwn(bboxDescriptor, 'value')) { issues.push(problem(`lines[${lineIndex}].words[${wordIndex}].boundingBox`, 'OWN_DATA_REQUIRED', 'must be an own data property')); malformed = true; break }; words.push({ text: text.value, confidence: confidence.value, ...(bboxDescriptor ? { boundingBox: bboxDescriptor.value as PixelRect } : {}) }) }
      if (malformed) { issues.push(problem(`lines[${lineIndex}]`, 'MALFORMED_WORD', 'word must contain safe text and confidence')); continue }
      const parsed = labelOf(words); if (!parsed) continue; const entry = evidence(parsed.values, size); if (!entry.ok) { if (entry.code !== 'EMPTY_VALUE') issues.push(problem(`lines[${lineIndex}]`, entry.code, entry.message)); continue }
      if (parsed.label.name === 'matchRef') { active.market = undefined; const previous = matches.get(entry.value.value); if (previous) { issues.push(problem(`lines[${lineIndex}]`, 'DUPLICATE_MATCH_REF', 'match reference is repeated')); active.match = previous } else { const key = idFrom(createUuid, `lines[${lineIndex}].entityKey`, 'entity', issues, allocatedEntityKeys, allocatedFieldIds); if (!key) { active.match = undefined; continue }; matches.set(entry.value.value, key); active.match = key }; continue }
      if (parsed.label.name === 'marketRef') { if (!active.match) { issues.push(problem(`lines[${lineIndex}]`, 'ORPHAN_MARKET_REF', 'market reference must name a known active match')); continue }; const matchKey = matches.get(entry.value.value); if (!matchKey) { issues.push(problem(`lines[${lineIndex}]`, 'ORPHAN_MARKET_REF', 'market reference must exactly match a known MATCH REF')); active.market = undefined; continue }; const marketKey = idFrom(createUuid, `lines[${lineIndex}].entityKey`, 'entity', issues, allocatedEntityKeys, allocatedFieldIds); if (!marketKey) { active.market = undefined; continue }; active.market = marketKey; add('MARKET', marketKey, 'matchRef', { ...entry.value, value: matchKey }, `lines[${lineIndex}]`); if (exceededFieldLimit) break; continue }
      if (parsed.label.name === 'matchDate' || parsed.label.name === 'league' || parsed.label.name === 'homeTeam' || parsed.label.name === 'awayTeam' || parsed.label.name === 'kickoffTime') { if (active.match) add('MATCH', active.match, parsed.label.name, entry.value, `lines[${lineIndex}]`) }
      else if (active.market) add('MARKET', active.market, parsed.label.name, entry.value, `lines[${lineIndex}]`)
      if (exceededFieldLimit) break
    }
    const result = validateCandidateBatch({ schemaVersion: 'OCR_CANDIDATE_V2', processedImage: image.value.processedImage, fields }); if (!result.valid || issues.length > 0) return { valid: false, issues: [...issues, ...(result.valid ? [] : result.issues)] }; return { valid: true, value: result.value, issues }
  } catch { return { valid: false, issues: issues.length ? issues : [problem('$', 'UNSAFE_INPUT', 'input could not be safely mapped')] } }
}
